version: 2

jobs:
  hello:
    docker:
      - image: debian:stretch-slim
    steps:
      - run: echo 'Hello, world'


workflows:
  version: 2
  cron:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only: master
    jobs:
      - hello
