version: 2

jobs:
  hello:
    docker:
      - image: debian:stretch-slim
    steps:
      - run: echo 'Hello, world'


workflows:
  version: 2
  cron:
    triggers:
      - schedule:
          cron: "0 0 1 1 *"
          filters:
            branches:
              only: master
    jobs:
      - hello
